### PR TITLE
Highlight current results page

### LINKED ISSUE #62: highlight current page no.
**Describe the bug**
The current page is not highlighted when we search something.

**Expected behavior**
The current page should be highlighted/grayed out so that the user doesn't forget the current page number.

**Additional context**
Reading the documentation of [bulma.io](https://bulma.io/documentation/components/pagination/) may help.

### PR DESCRIPTION
**Pull request by chrisshyi**
Resolves #62 
Added HTML attribute to highlight the current page of search results.

### CODE REVIEW

**Comment by perun-01** [comment]
hey chrisshyi, even i tried to send a PR and there also the labeler failed.
maybe it is because of yaml file or some write protected issues. I am trying to find out. 
If you found out,  please share

**Comment by Bhupesh-V** [comment]
The github actions have not been correctly set up that's why it's failing.
You can work on this if you want to make sure to create the issue first.

**Comment by Animesh-Ghosh** [comment]
image
***Looks Blue.***

@Bhupesh-V OK to merge, unless colour needs to be changed.

**Comment by Bhupesh-V** [comment]
@chrisshyi  thanks for the contributions
sorry for the late merge :sweat_smile:

**Comment by Bhupesh-V** [comment]
@all-contributor add @chrisshyi for code

**Comment by Bhupesh-V** [comment]
@all-contributors please add @chrisshyi   for code

**Pull request merged**
