### PR TITLE
Remove run error on focusMe

### PR DESCRIPTION
**Pull request by liorbentov**

### CODE REVIEW

**Comment by Animesh-Ghosh** [comment]
Please create an issue first before creating a Pull Request.

It helps in associating PRs with the issues that they are solving.

**Comment by Animesh-Ghosh** [comment]
A description would have also sufficed. Creating an issue for errors may be a good idea, but creating issues for increasing readability might be a bit much.

Please update #49 accordingly. I wasn't thinking as well.

**Comment by Animesh-Ghosh** [comment]
This PR solves what run error exactly? Is it the ConnectionAbortedError? Please add a description about what exactly this change solves.

If it's a small issue (ex. readabilty), then only description may suffice. However, if it's a major issue creating an Issue would help document what changed and why.

**Comment by liorbentov** [comment]
Sorry for that, it has been a long time since I've posted a PR... When entering the About page, there is a console error that is caused by focusMe implementation.

**Comment by Animesh-Ghosh** [comment]
You meant the browser console? That took me a while to figure out.

While it does get rid of the TypeError, a ReferenceError comes up in the Homepage.

**Comment by liorbentov** [comment]
@Animesh-Ghosh, fixed

**Comment by Animesh-Ghosh** [comment]
Fixing TypeError introduces a ReferenceError.

**Comment by liorbentov** [comment]
Where? What are the steps to reproduce?

**Comment by Animesh-Ghosh** [comment]
Sorry, it seems removing the **TypeError** doesn't introduce the **ReferenceError**, it already was there before.

Steps to reproduce:
1. Run server.
2. Search for tutorial.
3. Let the page load.
4. Check browser console.

**Comment by liorbentov** [comment]
@Animesh-Ghosh , I think it's right to open an issue/bug for that if it's not related.  What do you say?

**Comment by Animesh-Ghosh** [comment]
Really need to update the **`CONTRIBUTING.md`** file. 😅

**Comment by liorbentov** [comment]
> Really need to update the **`CONTRIBUTING.md`** file. 😅

I don't think that's related as well 🤷‍♀  What do you want this file to say?
Does this PR resolve the error? Does it create a new one?
If it resolves the error and doesn't create a new one, I think it's right to merge it and stop the discussion, or at least move it to somewhere proper.

**Comment by liorbentov** [comment]
@Animesh-Ghosh , I've opened a PR (#54 ) for fixing the reference error.

**Comment by Bhupesh-V** [comment]
@liorbentov should i merge this one or #54 ?

**Pull request merged**
