### PR TITLE
Fix PWA

### LINKED ISSUE #36: PWA fix
**Describe the bug**
The PWA feature had been added previously but there seems to be some issue.

**Expected behavior**
An Add to Home Screen option should appear on android devices.

### PR DESCRIPTION
**Pull request by viktorstrate**
This pull request, resolves #36 

- Move service worker to root of site
- Improve service worker for better caching
- Improve manifest.json
- Add square icon for site (icon-192.png and icon-512.png)

Screenshot 2019-10-14 at 22 07 38

## Lighthouse result

Screenshot 2019-10-14 at 22 06 50

### CODE REVIEW

**Comment by Animesh-Ghosh** [comment]
Hey man, you need to follow the Django file structure conventions.

**Comment by viktorstrate** [comment]
Are you refering to the `service-worker.js` not being located under `/static/`? If not please correct me.

I needed to move the service worker to the root, otherwise it can only be used for files under the `/static/` subdirectory. This has to do with the scope of service workers, and this was acually the reason why it didn't work before.

See [Google's Introduction to Service Worker - Registration and Scope](https://developers.google.com/web/ilt/pwa/introduction-to-service-worker#registration_and_scope)

> The scope of the service worker determines which files the service worker controls, in other words, from which path the service worker will intercept requests. The default scope is the location of the service worker file, and extends to all directories below. **So if service-worker.js is located in the root directory, the service worker will control requests from all files at this domain.**

Because of this it is the standard to always have the service worker at the root of the site.

It is possible to have a service worker, under a subdirectory, control the root of the site, but a HTTP header would have to be set by the server to allow this, as this can be a security problem.
See [Service-Worker-Allowed HTTP Header](https://w3c.github.io/ServiceWorker/#service-worker-script-response)

**Comment by viktorstrate** [comment]
I've changed name and logo in the latest commit

**Comment by Bhupesh-V** [comment]
@viktorstrate  Thanks for your contributions :tada:  , the changes will be live soon.
Sorry for the late merge :crying_cat_face:

**Comment by Bhupesh-V** [comment]
@all-contributors please add @viktorstrate  for code

**Pull request merged**
