### PR TITLE
Implemented the caching db query for tags page

### PR DESCRIPTION
**Pull request by vikneswaran20**
- Implemented the caching for query all the tags in tags page
- Added the cache_constant.py file since we need to use the same cache in multiple places.
- Currently used in-memory cache. But in the future, it can extended to the external caching system like Redis or Memcached with simple configurations in setting.py file like this

```python
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}
```

### CODE REVIEW

**Comment by Animesh-Ghosh** [comment]
How did you setup the cache?

**Comment by vikneswaran20** [comment]
Currently I have implemented the in memory cache provided by Django by default. No need to setup any external cache. If we need we can setup memcached or redis separately and configure it in django

**Comment by Animesh-Ghosh** [comment]
I meant did you run any Django **`manage.py`** commands?

**Comment by vikneswaran20** [comment]
No not needed. Just see caching as some thing like how you connect database. Now I used Django’s inbuilt cache which is some thing like using sqlite, no additional configuration needed. Later we can extend it to the PostgreSQL or MySQL. Similarly if we implement it later we can also extend the inbuilt cache to external caching system like redis or memcahed. I just used DB here for analogy to understand how to implement caching in django.

**Comment by Bhupesh-V** [comment]
@vikneswaran20  thanks a lot for this PR :heart_decoration: , sorry for the late merge have been busy :sweat_smile:

**Comment by Bhupesh-V** [comment]
@all-contributors please add @vikneswaran20  for code

**Pull request merged**
